language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
script:
  - pytest --cov=app test.py
  - coverage
  - coveralls
  - codeclimate-test-reporter
after_success:
  - coveralls
  - codeclimate-test-reporter
