language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=app test.py
  - coverage
  - coveralls
after_success:
  - coveralls
pytest test.py --cov=app --cov-report term-missing
